app:
  config:
    server:
      image-write-directory: /tesseract-temp-images  
    ocr:
      tesseract:
        tessdata-location: /tesseract/tessdata/

spring:
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/porua?useSSL=false&allowPublicKeyRetrieval=true
