app:
  config:
    image-write-directory: '/tesseract-temp-images'  
    tessdata-location: '/tesseract/tessdata/'
    dynamic-jpa-write-directory: '/dynamic-jpa-classes'

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/porua?useSSL=false&allowPublicKeyRetrieval=true
  liquibase:
    enabled: false
